Repository AY2324S1-CS2103T-F12-2/tp, pull requests merged in 2023-10, with the labels that each got.

#22 Update PPP
  docs/team/bearypop.md
Labels: documentation

#21 Updated AboutsUs page, skeletal PPP and User Guide
  README.md
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/add.png
  docs/images/desktop.ini
  docs/images/wnchan.png
  docs/team/wnchan.md
Labels: documentation

#20 Updated README contents and Ui mockup
  README.md
  docs/images/Ui.png
  docs/images/desktop.ini
Labels: documentation

#25 Edited UserGuide
  docs/UserGuide.md
Labels: documentation

#28 Edited UserGuide
  docs/UserGuide.md
Labels: documentation

#40 Update delete ug2
  docs/UserGuide.md
  docs/images/delete.png
Labels: documentation

#42 Update user stories, glossary, NFRs, use cases in DG
  docs/DeveloperGuide.md
Labels: documentation

#43 Update AboutUs.md
  docs/AboutUs.md
Labels: documentation

#33 Edited the "Add" feature
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Description.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Major.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/SocialMediaLink.java
  src/main/java/seedu/address/model/person/Year.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: documentation, enhancement, type.story

#48 Add edit feature in DG
  docs/DeveloperGuide.md
Labels: documentation

#53 Updated image for 'Add' feature
  docs/images/add.png
  src/main/java/seedu/address/model/person/Major.java
Labels: documentation

#49 Delete by email feature
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Major.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalEmails.java
Labels: enhancement

#46 Add edit feature in UG
  docs/UserGuide.md
Labels: documentation

#56 Add edit feature
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/wnchan.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Major.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/socialmedialink/SocialMediaLink.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedSocialMedia.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalEmails.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#60 Branch fix deleteparsertest
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: bug

#61 Update User Guide
  docs/UserGuide.md
  docs/images/exit.png
  docs/team/bearypop.md
Labels: documentation

#64 Edit most of the test files
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: priority.medium

#66 Fix edit command test
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Description.java
  src/main/java/seedu/address/model/person/Major.java
  src/main/java/seedu/address/model/person/SocialMediaLink.java
  src/main/java/seedu/address/model/person/Year.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/person/DescriptionTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/MajorTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/YearTest.java
  src/test/java/seedu/address/model/socialmedialink/SocialMediaLinkTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: bug

#68 Improve UI
  build.gradle
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/PersonListCard.fxml
Labels: enhancement, priority.high

#80 Hyperlink social media
  docs/DeveloperGuide.md
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/ui/JavaFxInitializer.java
  src/test/java/seedu/address/ui/PersonCardTest.java
Labels: enhancement, type.story, priority.high

#82 Help command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/helpMessage.png
  docs/images/helpWindow.png
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/address/ui/HelpWindowTest.java
Labels: documentation, enhancement, type.story, priority.medium

#85 Update DG for Tutorial Implementation
  docs/DeveloperGuide.md
  docs/diagrams/Person.puml
  docs/images/PersonClassDiagram.png
Labels: documentation

#88 Add task classes
  src/main/java/seedu/address/model/group/exceptions/TaskException.java
  src/main/java/seedu/address/model/group/tasks/Deadline.java
  src/main/java/seedu/address/model/group/tasks/Event.java
  src/main/java/seedu/address/model/group/tasks/Task.java
  src/main/java/seedu/address/model/group/tasks/TaskList.java
  src/main/java/seedu/address/model/group/tasks/TaskStatus.java
  src/main/java/seedu/address/model/group/tasks/Todo.java
  src/test/java/seedu/address/model/group/tasks/DeadlineTest.java
  src/test/java/seedu/address/model/group/tasks/TodoTest.java
Labels: enhancement, type.story, priority.medium

#90 Update documentation 1.3
  docs/UserGuide.md
  docs/images/socialMediaLinks.png
Labels: documentation, priority.high

#95 Update docs v1.3
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/multipleLinks.png
Labels: documentation

#92 Filter feature
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tutorial/Tutorial.java
  src/main/java/seedu/address/model/tutorial/TutorialContainsSlotsPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedSocialMedia.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorial.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/tutorial/TutorialContainsSlotsPredicateTest.java
  src/test/java/seedu/address/model/tutorial/TutorialTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#96 Update ug screenshots
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/add.png
  docs/images/create.png
  docs/images/delete.png
  docs/images/edit.png
  docs/images/exit.png
  docs/images/findAlexResult.png
  docs/images/help.png
  docs/images/list.png
Labels: documentation

#98 Nationality and Gender Fields Implementation
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/group/tasks/DeadlineTest.java
  src/test/java/seedu/address/model/group/tasks/TodoTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement, type.story

#99 Fix bug hyperlink
  src/main/java/seedu/address/ui/PersonCard.java
Labels: bug
