Repository AY2324S1-CS2103T-F12-2/tp, pull requests merged in 2023-11, with the labels that each got.

#106 Tasks feature
  src/main/java/seedu/address/commons/util/JsonParserUtil.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/commands/TasksCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/TasksCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/exceptions/GroupNotFoundException.java
  src/main/java/seedu/address/model/group/tasks/Deadline.java
  src/main/java/seedu/address/model/group/tasks/Event.java
  src/main/java/seedu/address/model/group/tasks/Task.java
  src/main/java/seedu/address/model/group/tasks/TaskInitializer.java
  src/main/java/seedu/address/model/group/tasks/TaskList.java
  src/main/java/seedu/address/model/group/tasks/TaskModule.java
  src/main/java/seedu/address/model/group/tasks/TaskStatus.java
  src/main/java/seedu/address/model/group/tasks/Todo.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/group/tasks/DeadlineTest.java
  src/test/java/seedu/address/model/group/tasks/TodoTest.java
Labels: enhancement, priority.high

#103 Find group feature
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindGroupCommand.java
  src/main/java/seedu/address/logic/commands/JoinCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindGroupCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/GroupContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FindGroupCommandTest.java
  src/test/java/seedu/address/logic/parser/FindGroupCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/group/GroupContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalGroups.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#105 Leave group command
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/JoinCommand.java
  src/main/java/seedu/address/logic/commands/LeaveCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/LeaveCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/LeaveCommandTest.java
  src/test/java/seedu/address/logic/parser/LeaveCommandParserTest.java
  src/test/java/seedu/address/ui/PersonCardTest.java
Labels: enhancement

#111 Delete group command
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteGroupCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteGroupCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteGroupCommandParserTest.java
Labels: enhancement, type.story, priority.high

#112 Mark and unmark task
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/mark.png
  docs/images/unmark.png
  src/main/java/seedu/address/commons/util/JsonParserUtil.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/TasksCommand.java
  src/main/java/seedu/address/logic/commands/UnMarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UnMarkCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/exceptions/GroupNotFoundException.java
  src/main/java/seedu/address/model/group/tasks/Task.java
  src/main/java/seedu/address/model/group/tasks/TaskInitializer.java
  src/main/java/seedu/address/model/group/tasks/TaskList.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/test/java/seedu/address/model/group/tasks/DeadlineTest.java
  src/test/java/seedu/address/model/group/tasks/TodoTest.java
Labels: documentation, enhancement, type.story, priority.medium

#115 Create pop-up for clear
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/ui/ConfirmationPopup.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/ClearConfirmationPopup.css
  src/main/resources/view/ClearConfirmationPopup.fxml
  src/main/resources/view/MainWindow.fxml
Labels: enhancement, type.story, priority.high

#122 Fix documentation
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/JoinCommand.java
  src/main/java/seedu/address/logic/commands/LeaveCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/tasks/Deadline.java
  src/main/java/seedu/address/model/group/tasks/Event.java
  src/main/java/seedu/address/model/group/tasks/Task.java
  src/main/java/seedu/address/model/group/tasks/Todo.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Description.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/Major.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Nationality.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Year.java
  src/main/java/seedu/address/model/socialmedialink/SocialMediaLink.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorial.java
Labels: documentation

#123 Fix delete group, mark and unmark bugs
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/parser/DeleteGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/UnMarkCommandParser.java
Labels: bug

#124 Fixed minor bugs in task feature
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindGroupCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/JoinCommand.java
  src/main/java/seedu/address/logic/commands/LeaveCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListGroupCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/TasksCommand.java
  src/main/java/seedu/address/logic/commands/UnMarkCommand.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/TasksCommandParser.java
  src/main/java/seedu/address/logic/parser/UnMarkCommandParser.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/tasks/Deadline.java
  src/main/java/seedu/address/model/group/tasks/Event.java
  src/main/java/seedu/address/model/group/tasks/Task.java
  src/main/java/seedu/address/model/group/tasks/TaskInitializer.java
  src/main/java/seedu/address/model/group/tasks/TaskList.java
  src/main/java/seedu/address/model/group/tasks/TaskStatus.java
  src/main/java/seedu/address/model/group/tasks/Todo.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
Labels: priority.medium

#118 Add filter group feature
  src/main/java/seedu/address/logic/commands/FilterGroupCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterGroupCommandParser.java
  src/main/java/seedu/address/model/group/GroupBelongsTutorialPredicate.java
  src/test/java/seedu/address/logic/commands/FilterGroupCommandTest.java
Labels: enhancement

#120 Add check feature
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/CheckCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CheckCommandParser.java
Labels: enhancement

#125 Fix bug
  src/main/java/seedu/address/logic/parser/DeleteGroupCommandParser.java
Labels: bug

#128 Fix bugs for filter & check
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/CheckCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FilterGroupCommand.java
Labels: bug

#129 Reimplement clear in Menubar
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: bug

#133 Update UG DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#135 Bug fix
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/JoinCommand.java
  src/main/java/seedu/address/logic/commands/LeaveCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: bug

#134 Update ug dg
  docs/UserGuide.md
Labels: documentation

#139 Fix typo
  docs/UserGuide.md
Labels: documentation

#178 Update UG for Expected Output of tasks
  docs/UserGuide.md
Labels: documentation

#180 Fix clear ug
  docs/UserGuide.md
  docs/images/clearCancel.png
Labels: bug, documentation

#182 Update ppp
  docs/UserGuide.md
  docs/team/neyapraveen.md
Labels: documentation

#185 Edit UG
  docs/UserGuide.md
Labels: documentation

#187 Update DG image, DG and PPP
  docs/DeveloperGuide.md
  docs/images/DeleteSequenceDiagram.png
  docs/team/wnchan.md
Labels: documentation

#186 Add How to Use This Guide Section to UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/GroupListUI.png
  docs/images/StudentListUI.png
  docs/team/maj0-0.md
Labels: documentation

#191 Add PPP draft
  docs/team/pearlynnt.md
Labels: documentation

#192 Fix test cases
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/ui/ConfirmationPopup.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteGroupCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteGroupCommandParserTest.java
  src/test/java/seedu/address/ui/ConfirmationPopupTest.java
  src/test/java/seedu/address/ui/JavaFxInitializer.java
  src/test/java/seedu/address/ui/PersonCardTest.java
Labels: bug

#193 Update Documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/GroupModelClassDiagram.puml
  docs/diagrams/PersonModelClassDiagram.puml
  docs/images/GroupModelClassDiagram.png
  docs/images/PersonModelClassDiagram.png
  docs/team/maj0-0.md
Labels: documentation

#198 Add javadocs check group
  src/main/java/seedu/address/logic/commands/CheckCommand.java
Labels: documentation

#199 Style ug
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#201 Update diagram for DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/StudentConnectLogo.png
Labels: documentation

#210 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagramNew.png
Labels: documentation

#213 Edit help message
  docs/UserGuide.md
  docs/team/neyapraveen.md
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: documentation

#214 Update Documentation
  docs/UserGuide.md
  docs/images/checkGroup.png
  docs/images/helpMessage.png
  docs/team/maj0-0.md
  src/test/java/seedu/address/logic/commands/TasksCommandTest.java
  src/test/java/seedu/address/model/group/tasks/TaskListTest.java
Labels: documentation

#215 Fix documentation bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#220 Edit PPP
  docs/team/wnchan.md
Labels: documentation

#219 Update ppp 1.4
  docs/team/neyapraveen.md
Labels: documentation

#221 Edit PPP
  docs/team/wnchan.md
Labels: documentation

#222 Edit PPP
  docs/team/neyapraveen.md
Labels: documentation

#225 Edit PPP
  docs/team/wnchan.md
Labels: documentation

#226 Edit PPP
  docs/team/neyapraveen.md
Labels: documentation

#229 Edit PPP
  docs/team/wnchan.md
Labels: bug

#228 Edit PPP
  docs/team/neyapraveen.md
Labels: documentation

#247 Fix UG bug
  docs/UserGuide.md
Labels: documentation
